// Package lists. Mirrors the six PKG_* arrays in install.sh, in install order.
// Keep this file data-only so swapping/adding packages doesn't touch main.rs.

pub struct Group {
    pub label: &'static str,
    pub pkgs: &'static [&'static str],
}

pub const GROUPS: &[Group] = &[
    Group { label: "Core (Niri / Noctalia / Wayland)", pkgs: CORE },
    Group { label: "Shell & CLI tools",                pkgs: SHELL },
    Group { label: "Fonts & Theming",                  pkgs: FONTS },
    Group { label: "Development",                      pkgs: DEV },
    Group { label: "Cybersecurity",                    pkgs: SEC },
    Group { label: "BlackArch",                        pkgs: BLACKARCH },
];

// Core Wayland / Niri / Noctalia
const CORE: &[&str] = &[
    "niri",
    "noctalia-qs",
    "noctalia-shell",
    "xwayland-satellite",
    "awww",
    "fuzzel",
    "wl-clipboard",
    "cliphist",
    "wl-clip-persist",
    "brightnessctl",
    "polkit-gnome",
    "xdg-desktop-portal-gnome",
    "xdg-utils",
    "qt5-wayland",
    "qt6-wayland",
    "grim",
    "slurp",
    "wlogout",
    "swaybg",
    "mako",
    "wev",
    "ddcutil",
    "cava",
    "wlsunset",
    "greetd",
    "greetd-tuigreet",
    "sddm",
    "sddm-astronaut-theme",
    "sddm-theme-noctalia-git",
    "sddm-theme-tokyo-night-git",
    "sddm-sugar-dark",
    "sddm-lain-wired-theme",
    "qt5-graphicaleffects",
    "qt5-quickcontrols2",
    "qt6-declarative",
    "layer-shell-qt",
    "thunar",
    "gvfs",
    "firefox",
    "pipewire",
    "pipewire-audio",
    "pipewire-pulse",
    "pipewire-alsa",
    "pipewire-jack",
    "wireplumber",
    "alsa-utils",
    "sof-firmware",
    "pavucontrol",
    "pwvucontrol",
    // power-profiles-daemon feeds the Noctalia battery widget + provides
    // balanced/performance profiles via D-Bus.
    "power-profiles-daemon",
];

// Terminal / Shell / Prompt
const SHELL: &[&str] = &[
    "kitty",
    "tmux",
    "zsh",
    "starship",
    "fzf",
    "fd",
    "ripgrep",
    "eza",
    "bat",
    "zoxide",
    "direnv",
    "jq",
    "yq",
    "tree",
    "btop",
    "fastfetch",
    "less",
    "man-db",
];

// Fonts / Theming
const FONTS: &[&str] = &[
    "ttf-jetbrains-mono-nerd",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "papirus-icon-theme",
    "bibata-cursor-theme",
    "tokyonight-gtk-theme-git",
    "kvantum",
    "qt5ct",
    "qt6ct",
];

// Development
const DEV: &[&str] = &[
    "neovim",
    "git",
    "git-delta",
    "libsecret",
    "lazygit",
    "github-cli",
    "base-devel",
    "cmake",
    "gcc",
    "gdb",
    "lldb",
    "clang",
    "rust",
    "go",
    "python",
    "python-pip",
    "python-virtualenv",
    "nodejs",
    "npm",
    "docker",
    "docker-compose",
    "podman",
    "stow",
    "editorconfig-core-c",
    "stylua",
    "shfmt",
    "prettierd",
    "tree-sitter-cli",
    "opencode-bin",
    "lmstudio-bin",
    // GPU + media diagnostic utilities (vendor-agnostic):
    //   vulkan-tools  -> vulkaninfo (verify the Vulkan ICD is loaded).
    //   libva-utils   -> vainfo (verify VA-API hardware decode).
    //   mesa-utils    -> glxinfo + eglinfo for OpenGL diagnostics.
    //   mangohud      -> overlay for CPU/GPU/framerate during testing.
    // NOTE: install your GPU's Vulkan ICD separately (vulkan-radeon /
    // vulkan-intel / nvidia-utils) -- not pinned here so the script stays
    // hardware-neutral.
    "vulkan-tools",
    "libva-utils",
    "mesa-utils",
    "mangohud",
];

// Cybersecurity / Pentesting (core tools -- available in official + chaotic-aur)
const SEC: &[&str] = &[
    "nmap",
    "masscan",
    "rustscan",
    "wireshark-qt",
    "tcpdump",
    // openbsd-netcat is preferred over gnu-netcat: both provide /usr/bin/nc
    // and conflict with each other. The OpenBSD variant is the de facto
    // standard in pentesting / CTF tooling.
    "openbsd-netcat",
    "bind",
    "whois",
    "traceroute",
    "curl",
    "wget",
    "nikto",
    "sqlmap",
    "hydra",
    "john",
    "hashcat",
    "aircrack-ng",
    "burpsuite",
    "metasploit",
    "gobuster",
    "feroxbuster",
    "ffuf",
    "dirb",
    "dirsearch",
    "wfuzz",
    "enum4linux",
    "smbclient",
    "smbmap",
    "binwalk",
    "foremost",
    "steghide",
    "perl-image-exiftool",
    "radare2",
    "ghidra",
    "checksec",
    "python-pwntools",
    "impacket",
    "responder",
    "tor",
    "openvpn",
    "wireguard-tools",
    "net-tools",
    "arp-scan",
    "nbtscan",
    "fping",
    "netdiscover",
    "subfinder",
    "amass",
    "httpx",
    "nuclei",
    "zaproxy",
    "sslscan",
    "testssl.sh",
    "sslyze",
    "trivy",
    "net-snmp",
    "onesixtyone",
    "strace",
    "ltrace",
    "socat",
    "proxychains-ng",
    "macchanger",
    "strongswan",
    "vpnc",
    "ike-scan",
    "powershell-bin",
];

// BlackArch tools (from blackarch repo)
const BLACKARCH: &[&str] = &[
    // ── Recon / OSINT ──────────────────────────────────────────────────────
    "blackarch-recon",
    "theharvester",
    "sherlock",
    "maltego",
    "spiderfoot",
    "recon-ng",
    "photon",
    "osrframework",
    "whatweb",
    "wafw00f",
    "dnsrecon",
    "fierce",
    "sublist3r",
    "assetfinder",
    "hakrawler",
    "gau",
    "waybackurls",
    "katana",
    "gospider",
    "meg",
    "unfurl",
    "gf",
    "dmitry",
    "legion",

    // ── DNS / subdomain ────────────────────────────────────────────────────
    "dnsenum",
    "dnsmap",
    "dnstracer",
    "massdns",
    "shuffledns",
    "puredns",
    "dnsx",
    "alterx",
    "tlsx",
    "mapcidr",
    "asnmap",
    "cdncheck",
    "naabu",
    "uncover",
    "chaos-client",

    // ── Web exploitation ───────────────────────────────────────────────────
    "blackarch-webapp",
    "wpscan",
    "xsser",
    "commix",
    "dalfox",
    "arjun",
    "paramspider",
    "jwt-tool",
    "graphqlmap",
    "nosqlmap",
    "cadaver",
    "davtest",
    "skipfish",
    "dirbuster",

    // ── Exploitation frameworks ────────────────────────────────────────────
    "blackarch-exploitation",
    "exploitdb",
    "routersploit",
    "netexec",
    "evil-winrm",
    "covenant",
    "sliver",
    "empire",
    "powersploit",
    "unicorn-powershell",
    "veil",
    "backdoor-factory",
    "beef-xss",

    // ── Active Directory / Windows ─────────────────────────────────────────
    "kerbrute",
    "enum4linux-ng",
    "certipy",
    "adidnsdump",
    "bloodyad",
    "ldeep",
    "windapsearch",
    "sprayhound",
    "manspider",
    "coercer",
    "pkinittools",
    "sccmhunter",
    "nishang",
    "windows-binaries",

    // ── Password attacks ───────────────────────────────────────────────────
    "blackarch-cracker",
    "hashcat-utils",
    "hcxtools",
    "hcxdumptool",
    "cewl",
    "crunch",
    "medusa",
    "patator",
    "thc-pptp-bruter",
    "hash-identifier",
    "python-name-that-hash",
    "rsmangler",
    "username-anarchy",
    "cupp",
    "changeme",

    // ── Wireless ───────────────────────────────────────────────────────────
    "blackarch-wireless",
    "bettercap",
    "wifite",
    "pixiewps",
    "reaver",
    "hostapd-mana",
    "fluxion",
    "airgeddon",
    "yersinia",

    // ── Privilege escalation / post-exploitation ───────────────────────────
    "peass",
    "pspy",
    "linenum",
    "linux-exploit-suggester",
    "mimikatz",
    "bloodhound",
    "chisel",
    "ligolo-ng",
    "pwncat",

    // ── Reversing / binary ─────────────────────────────────────────────────
    "blackarch-reversing",
    "rizin",
    "cutter",
    "iaito",
    "retdec",
    "angr",
    "ropper",
    "one_gadget",
    "patchelf",

    // ── Mobile security ────────────────────────────────────────────────────
    "android-apktool",
    "jadx",
    "dex2jar",
    "objection",
    "drozer",
    "apkleaks",
    "mobsf",

    // ── Forensics ──────────────────────────────────────────────────────────
    "blackarch-forensic",
    "autopsy",
    "bulk-extractor",
    "scalpel",
    "yara",
    "volatility3",
    "pdf-parser",
    "oletools",
    "regripper",

    // ── Networking / MITM ──────────────────────────────────────────────────
    "blackarch-networking",
    "mitmproxy",
    "ettercap",
    "tcpreplay",
    "hping",
    "ncrack",
    "dsniff",
    "sslstrip",
    "dns2tcp",
    "iodine",
    "ptunnel",
    "snmpcheck",

    // ── Social engineering ─────────────────────────────────────────────────
    "blackarch-social",
    "social-engineer-toolkit",
    "gophish",
    "evilginx",

    // ── Crypto ─────────────────────────────────────────────────────────────
    "blackarch-crypto",
    "hashpump",
    "rsactftool",
    "featherduster",
    "python-pycryptodome",
    "xortool",

    // ── Stego ──────────────────────────────────────────────────────────────
    "blackarch-stego",
    "stegseek",
    "zsteg",
    "stegsolve",
    "openstego",
    "snow",

    // ── Fuzzing ────────────────────────────────────────────────────────────
    "blackarch-fuzzer",
    "afl++",
    "boofuzz",
    "radamsa",
    "zzuf",

    // ── Secret scanning / supply chain ─────────────────────────────────────
    "trufflehog",
    "gitleaks",
    "proxify",
    "interactsh-client",
    "simplehttpserver",

    // ── Cloud security ─────────────────────────────────────────────────────
    "pacu",
    "scoutsuite",
    "prowler",

    // ── Wordlists / resources ──────────────────────────────────────────────
    "seclists",
    "wordlistctl",
    "wordlists",
    "dirbuster-wordlists",
    "fuzzdb",
    "payloadsallthethings",
    "webshells",
    "cyberchef-electron",
];
