#!/usr/bin/env bash
# =============================================================================
# deploy.sh -- Symlink dotfiles into $HOME
# Run: chmod +x deploy.sh && ./deploy.sh
# =============================================================================
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

GRN='\033[0;32m'
BLU='\033[0;34m'
YLW='\033[1;33m'
RST='\033[0m'

info() { echo -e "${BLU}[*]${RST} $*"; }
ok() { echo -e "${GRN}[+]${RST} $*"; }
warn() { echo -e "${YLW}[!]${RST} $*"; }

BACKUP_DIR="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

link_item() {
  local src="$1"
  local dest="$2"

  # Backup existing files/dirs that are NOT already our symlinks
  if [[ -e "$dest" || -L "$dest" ]]; then
    if [[ "$(readlink -f "$dest" 2>/dev/null)" == "$(readlink -f "$src" 2>/dev/null)" ]]; then
      return # already linked
    fi
    mkdir -p "$BACKUP_DIR"
    local rel="${dest#"$HOME"/}"
    mkdir -p "$BACKUP_DIR/$(dirname "$rel")"
    mv "$dest" "$BACKUP_DIR/$rel"
    warn "Backed up: ~/$rel -> $BACKUP_DIR/$rel"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -sf "$src" "$dest"
  ok "Linked: $src -> $dest"
}

echo ""
info "=== Deploying dotfiles from $DOTFILES ==="
echo ""

# ── .config directories ───────────────────────────────────────────────────
CONFIG_DIRS=(
  niri
  noctalia
  kitty
  fuzzel
  nvim
  tmux
  lazygit
  "systemd/user"
  opencode
  wal
  fastfetch
  neofetch
  gtk-3.0
  gtk-4.0
  qt5ct
  qt6ct
)

for dir in "${CONFIG_DIRS[@]}"; do
  link_item "$DOTFILES/.config/$dir" "$HOME/.config/$dir"
done

# ── Home-level dotfiles ────────────────────────────────────────────────────
link_item "$DOTFILES/.zshrc" "$HOME/.zshrc"
link_item "$DOTFILES/.gitignore_global" "$HOME/.gitignore_global"
link_item "$DOTFILES/.editorconfig" "$HOME/.editorconfig"

# ── Git config (tracked file deployed under XDG, NOT to ~/.gitconfig) ─────
# Symlinking the tracked .gitconfig directly to ~/.gitconfig would let any
# `git config --global ...` invocation mutate the tracked repo file (since
# git follows symlinks when writing). Instead we deploy the tracked config
# to a neutral path and put a tiny untracked stub at ~/.gitconfig that
# [include]s it. Stub mutations stay machine-local; repo stays clean.
mkdir -p "$HOME/.config/git"
link_item "$DOTFILES/.gitconfig" "$HOME/.config/git/dotfiles.config"

# Replace any prior symlink-to-tracked at ~/.gitconfig with the include stub.
if [[ -L "$HOME/.gitconfig" ]] \
  && [[ "$(readlink -f "$HOME/.gitconfig")" == "$(readlink -f "$DOTFILES/.gitconfig")" ]]; then
  rm "$HOME/.gitconfig"
  info "Removed legacy symlink: ~/.gitconfig -> \$DOTFILES/.gitconfig"
fi
if [[ ! -e "$HOME/.gitconfig" ]]; then
  cat >"$HOME/.gitconfig" <<'EOF'
# ~/.gitconfig -- per-machine stub generated by deploy.sh. NOT tracked.
#
# Tracked dotfiles config lives at ~/.config/git/dotfiles.config (symlink
# into $DOTFILES). Identity + signing live in ~/.gitconfig.local. Any
# `git config --global ...` mutations land HERE so the dotfiles repo stays
# clean of machine-specific drift.
[include]
    path = ~/.config/git/dotfiles.config
[include]
    path = ~/.gitconfig.local
EOF
  ok "Wrote ~/.gitconfig stub"
fi

# ── Git identity (~/.gitconfig.local, not tracked) ─────────────────────────
# The ~/.gitconfig stub above [include]s ~/.gitconfig.local. We generate it
# here so new users don't accidentally commit under the repo author's
# identity.
GITCONFIG_LOCAL="$HOME/.gitconfig.local"
if [[ ! -f "$GITCONFIG_LOCAL" ]]; then
  info "Setting up git identity (~/.gitconfig.local) ..."
  # Prefer environment, fall back to prompts. Skip prompts if stdin is not a tty.
  git_name="${GIT_USER_NAME:-}"
  git_email="${GIT_USER_EMAIL:-}"
  if [[ -z "$git_name" && -t 0 ]]; then
    read -rp "  git user.name  : " git_name
  fi
  if [[ -z "$git_email" && -t 0 ]]; then
    read -rp "  git user.email : " git_email
  fi
  git_name="${git_name:-Your Name}"
  git_email="${git_email:-you@example.com}"
  cat >"$GITCONFIG_LOCAL" <<EOF
# ~/.gitconfig.local -- per-machine identity + local overrides
# Included by ~/.gitconfig. Not tracked in the dotfiles repo.
[user]
    name = $git_name
    email = $git_email
    # Uncomment and point at your signing key to sign commits:
    # signingkey = ~/.ssh/id_ed25519.pub

# Uncomment to sign every commit (requires signingkey + allowed_signers):
# [commit]
#     gpgsign = true
EOF
  chmod 600 "$GITCONFIG_LOCAL"
  ok "Wrote $GITCONFIG_LOCAL (name=$git_name, email=$git_email)"
else
  ok "Existing ~/.gitconfig.local kept as-is."
fi

# ── Single-file ~/.config/* drops ──────────────────────────────────────────
# CONFIG_DIRS above only handles per-tool directories. Lone files in .config/
# need an explicit link line each.
if [[ -f "$DOTFILES/.config/starship.toml" ]]; then
  link_item "$DOTFILES/.config/starship.toml" "$HOME/.config/starship.toml"
fi

# ── Scripts ────────────────────────────────────────────────────────────────
mkdir -p "$HOME/.local/bin"
if [[ -d "$DOTFILES/.local/bin" ]]; then
  for script in "$DOTFILES/.local/bin"/*; do
    [[ -f "$script" ]] && link_item "$script" "$HOME/.local/bin/$(basename "$script")"
  done
fi

# ── Desktop entries (BlackArch tools) ─────────────────────────────────────
mkdir -p "$HOME/.local/share/applications"
if [[ -d "$DOTFILES/.local/share/applications" ]]; then
  info "Deploying BlackArch .desktop entries ..."
  for desktop in "$DOTFILES/.local/share/applications"/*.desktop; do
    [[ -f "$desktop" ]] && link_item "$desktop" "$HOME/.local/share/applications/$(basename "$desktop")"
  done
fi

# ── Wallpapers ─────────────────────────────────────────────────────────────
if [[ -d "$DOTFILES/wallpapers" ]]; then
  info "Deploying wallpapers to ~/Pictures/Wallpapers ..."
  mkdir -p "$HOME/Pictures/Wallpapers"
  for wp in "$DOTFILES/wallpapers"/*; do
    [[ -f "$wp" ]] && link_item "$wp" "$HOME/Pictures/Wallpapers/$(basename "$wp")"
  done
fi

# ── Enable user services ──────────────────────────────────────────────────
info "Enabling user systemd services ..."
systemctl --user daemon-reload 2>/dev/null || true
# These are started by niri spawn-at-startup, so we don't enable them
# as systemd services by default. Uncomment if you prefer systemd management:
# systemctl --user enable --now awww.service 2>/dev/null || true
# systemctl --user enable --now cliphist.service 2>/dev/null || true
systemctl --user enable --now hexstrike-server.service 2>/dev/null ||
  warn "  hexstrike-server.service failed to start (run install.sh first)"

# ── SDDM noctalia background sync (path + oneshot service) ────────────────
# Watches ~/.cache/noctalia/wallpapers.json; on change, runs the noctalia
# theme's sync-shell-wallpaper.sh as root (it writes into
# /usr/share/sddm/themes/noctalia/Assets/). Both the path and service have
# ConditionPathExists guards so they no-op on machines where the noctalia
# SDDM theme or the noctalia shell cache aren't present.
#
# Set DOTFILES_SKIP_SDDM_SYNC=1 to skip this block -- useful when you want
# the SDDM login wallpaper pinned to a static image, independent of the
# desktop wallpaper.
if [[ "${DOTFILES_SKIP_SDDM_SYNC:-0}" == "1" ]]; then
  info "Skipping SDDM noctalia background-sync (DOTFILES_SKIP_SDDM_SYNC=1)"
elif [[ -f "$DOTFILES/etc/systemd/system/sddm-noctalia-sync.path" ]]; then
  info "Deploying SDDM noctalia background-sync units ..."
  sudo cp "$DOTFILES/etc/systemd/system/sddm-noctalia-sync.path" \
    /etc/systemd/system/sddm-noctalia-sync.path
  sudo cp "$DOTFILES/etc/systemd/system/sddm-noctalia-sync.service" \
    /etc/systemd/system/sddm-noctalia-sync.service
  ok "  Copied sddm-noctalia-sync.{path,service}"
  sudo systemctl daemon-reload 2>/dev/null || true
  if [[ -d /usr/share/sddm/themes/noctalia ]]; then
    sudo systemctl enable --now sddm-noctalia-sync.path 2>/dev/null ||
      warn "  sddm-noctalia-sync.path failed to enable"
    ok "  sddm-noctalia-sync.path enabled"
  else
    warn "  /usr/share/sddm/themes/noctalia not found -- skipping enable"
  fi
fi

# ── SDDM config (system-wide, requires sudo) ─────────────────────────────
if [[ -d "$DOTFILES/etc/sddm.conf.d" ]]; then
  info "Deploying SDDM config to /etc/sddm.conf.d/ ..."
  sudo mkdir -p /etc/sddm.conf.d
  for conf in "$DOTFILES/etc/sddm.conf.d"/*; do
    [[ -f "$conf" ]] || continue
    sudo cp "$conf" "/etc/sddm.conf.d/$(basename "$conf")"
    ok "  Copied $(basename "$conf")"
  done
fi

# ── SDDM theme: upgrade-proof local copy of sddm-astronaut-theme ─────────
# pacman -Syu on `sddm-astronaut-theme` would overwrite our metadata.desktop
# ConfigFile= edit and any file we dropped in Themes/ or Backgrounds/.
# Solve it by copying the theme once into a sibling dir the package does
# not own, then customizing only the copy. Re-run `sudo rm -rf` on the
# local dir + `./deploy.sh` to refresh against upstream theme changes.
ASTRONAUT_SRC="/usr/share/sddm/themes/sddm-astronaut-theme"
ASTRONAUT_DIR="/usr/share/sddm/themes/sddm-astronaut-local"
if [[ -d "$ASTRONAUT_SRC" && -d "$DOTFILES/etc/sddm-themes" ]]; then
  info "Deploying local SDDM astronaut theme copy ..."
  if [[ ! -d "$ASTRONAUT_DIR" ]]; then
    sudo cp -a "$ASTRONAUT_SRC" "$ASTRONAUT_DIR"
    ok "  Created local theme dir: $ASTRONAUT_DIR"
  fi

  for conf in "$DOTFILES/etc/sddm-themes"/*.conf; do
    [[ -f "$conf" ]] || continue
    sudo cp "$conf" "$ASTRONAUT_DIR/Themes/$(basename "$conf")"
    ok "  Copied $(basename "$conf") -> local Themes/"
  done

  # Default SDDM background
  if [[ -f "$DOTFILES/wallpapers/samurai.png" ]]; then
    sudo cp "$DOTFILES/wallpapers/samurai.png" "$ASTRONAUT_DIR/Backgrounds/tokyonight.png"
    ok "  Set default SDDM background: samurai.png"
  fi

  # Point the local copy at the cyberpunk variant
  sudo sed -i 's|^ConfigFile=.*|ConfigFile=Themes/cyberpunk.conf|' "$ASTRONAUT_DIR/metadata.desktop"
  ok "  Activated: cyberpunk variant (in local copy)"
fi

echo ""
ok "=== Deployment complete ==="
echo ""

# Dynamic counts so this summary can't drift from reality.
script_count=$(find "$DOTFILES/.local/bin" -maxdepth 1 -type f 2>/dev/null | wc -l)
desktop_count=$(find "$DOTFILES/.local/share/applications" -maxdepth 1 -name '*.desktop' 2>/dev/null | wc -l)
wallpaper_count=$(find "$DOTFILES/wallpapers" -maxdepth 1 -type f 2>/dev/null | wc -l)
config_list=$(printf '%s,' "${CONFIG_DIRS[@]}" | sed 's/,$//')

info "Summary:"
info "  Configs: ~/.config/{${config_list}}"
info "  Shell:   ~/.zshrc"
info "  Git:     ~/.gitconfig, ~/.gitignore_global"
info "  Editor:  ~/.editorconfig"
info "  Prompt:  ~/.config/starship.toml"
info "  Scripts: ~/.local/bin/ (${script_count} scripts)"
info "  Apps:    ~/.local/share/applications/ (${desktop_count} desktop entries)"
info "  Walls:   ~/Pictures/Wallpapers/ (${wallpaper_count} wallpapers)"
info "  SDDM:    /etc/sddm.conf.d/niri.conf + astronaut cyberpunk theme"
info ""
if [[ -d "$BACKUP_DIR" ]]; then
  info "  Backups: $BACKUP_DIR"
fi
echo ""
info "Log out, select 'niri' from SDDM, and log back in."
info "Open a terminal (Super+Return) and run 'nvim' -- plugins install automatically."
echo ""
