# =============================================================================
# SDDM Config -- Niri Wayland Session
# /etc/sddm.conf.d/niri.conf
# Deployed by dotfiles/deploy.sh
# =============================================================================

[General]
Numlock=on

[Theme]
Current=noctalia
CursorTheme=Bibata-Modern-Classic
CursorSize=24

[Users]
MaximumUid=60513
MinimumUid=1000
